language: php

php:
 - "8.0"
 - "8.1"
 - "8.2"

matrix:
 include:
  - dist: focal

before_script:
 - composer self-update
 - composer --version
 - composer install -n --dev --prefer-source

script: composer run lint:check && composer run test
